FOSWIKI_ROOT?=~/foswiki/trunk/core
TARGET=\
  jquery.datatables.init.js \
  jquery.datatables.js \
  jquery.datatables.css \
  date-foswiki.js \
  currency.js \
  metrics.js

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm $(TARGET) *.gz

